vich_uploader:
    db_driver: orm

    mappings:
        Categories:
            uri_prefix: /images/Categories
            upload_destination: '%kernel.project_dir%/public/images/Categories'
        
        SousCategories:
            uri_prefix: /images/SousCategories
            upload_destination: '%kernel.project_dir%/public/images/SousCategories'

        Home:
            uri_prefix: /images/Home
            upload_destination: '%kernel.project_dir%/public/images/Home'

        userProfilPicture:
            uri_prefix: /images/userProfilPicture
            upload_destination: '%kernel.project_dir%/public/images/userProfilPicture'

        Carousel:
            uri_prefix: /images/Carousel
            upload_destination: '%kernel.project_dir%/public/images/Carousel'

        Services:
            uri_prefix: /images/Services
            upload_destination: '%kernel.project_dir%/public/images/Services'


        

